### ISSUE TITLE
Credential toJson() needed

### ISSUE THREAD

**Issue by aleexzhang** [WeBankFinTech/weidentity-java-sdk#40]
请新建一个PR，给`CredentialWrapper`和`Credential`两个类新实现两个函数: `toJson`和`toString`。两个函数功能一模一样，只是名字不同（可以实现`toString`，然后`toJson`来调用`toString`）。并且`CredentialWrapper`会调用`Credential`的`toString`来实现自己的`toString`。

_Originally posted by @gmzer in https://github.com/WeBankFinTech/weidentity-java-sdk/pull/37_

**Comment by chaoxinhu** [comment]
This is now in getCredentialJson(). Will change function name

**Comment by chaoxinhu** [comment]
This is now available in CredentialPojo
